# SPDX-License-Identifier: GPL-2.0

# Device Tree Blobs Overlay
ifdef CONFIG_MODEL_A127X
include arch/arm64/boot/dts/a12snsxx.mk
endif

ifdef CONFIG_MODEL_M127X
include arch/arm64/boot/dts/m12nsxx.mk
endif
